using System.Diagnostics.CodeAnalysis;

namespace Peers.Core.Common;

/// <summary>
/// Provides extension methods for working with generic dictionaries.
/// </summary>
public static class DictionaryExtensions
{
    extension<TKey, TValue>(IDictionary<TKey, TValue> source)
        where TKey : notnull
    {
        /// <summary>
        /// Gets the value associated with the specified key, or adds a new value generated by the specified function if
        /// the key does not exist.
        /// </summary>
        /// <param name="k">The key whose value to get or add.</param>
        /// <param name="f">A function used to generate a value for the specified key if it does not exist. The function receives the
        /// key as its argument and must not return null.</param>
        /// <returns>The value associated with the specified key. If the key was not present, the newly generated value is
        /// returned.</returns>
        public TValue GetOrAdd(TKey k, [NotNull] Func<TKey, TValue> f)
        {
            if (!source.TryGetValue(k, out var v))
            {
                source[k] = v = f(k);
            }

            return v;
        }
    }
}
