// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Peers.Modules.Kernel;

#nullable disable

namespace Peers.Modules.Migrations
{
    [DbContext(typeof(PeersContext))]
    partial class PeersContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-rc.1.25451.107")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence<int>("app_user_seq")
                .IncrementsBy(100);

            modelBuilder.HasSequence<int>("listing_seq")
                .IncrementsBy(100);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[normalized_name] IS NOT NULL");

                    b.ToTable("role", "id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("claim_value");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("role_claim", "id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("claim_value");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_claim", "id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("provider_display_name");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("user_login", "id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_role", "id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("user_token", "id");
                });

            modelBuilder.Entity("Peers.Modules.Catalog.Domain.Attributes.AttributeDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit")
                        .HasColumnName("is_required");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("key");

                    b.Property<int>("Kind")
                        .HasColumnType("int")
                        .HasColumnName("kind");

                    b.Property<int>("Position")
                        .HasColumnType("int")
                        .HasColumnName("position");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("int")
                        .HasColumnName("product_type_id");

                    b.HasKey("Id");

                    b.HasIndex("ProductTypeId", "Key")
                        .IsUnique();

                    b.HasIndex("ProductTypeId", "Position");

                    b.ToTable("attribute_definition", "catalog", t =>
                        {
                            t.HasCheckConstraint("CK_AD_IsVariant_EnumOnly", "[is_variant] = 0 OR [kind] = 5");

                            t.HasCheckConstraint("CK_AD_LookupTypeId_LookupOnly", "(\r\n    ([kind] = 6 AND [lookup_type_id] IS NOT NULL)\r\n    OR\r\n    ([kind] <> 6 AND [lookup_type_id] IS NULL)\r\n)");
                        });

                    b.HasDiscriminator<int>("Kind");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Peers.Modules.Catalog.Domain.Attributes.EnumAttributeOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EnumAttributeDefinitionId")
                        .HasColumnType("int")
                        .HasColumnName("enum_attribute_definition_id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("key");

                    b.Property<int?>("ParentOptionId")
                        .HasColumnType("int")
                        .HasColumnName("parent_option_id");

                    b.Property<int>("Position")
                        .HasColumnType("int")
                        .HasColumnName("position");

                    b.HasKey("Id");

                    b.HasIndex("ParentOptionId");

                    b.HasIndex("EnumAttributeDefinitionId", "Key")
                        .IsUnique();

                    b.HasIndex("EnumAttributeDefinitionId", "Position")
                        .IsUnique();

                    b.ToTable("enum_attribute_option", (string)null);
                });

            modelBuilder.Entity("Peers.Modules.Catalog.Domain.LookupAllowed", b =>
                {
                    b.Property<int>("ProductTypeId")
                        .HasColumnType("int")
                        .HasColumnName("product_type_id");

                    b.Property<int>("TypeId")
                        .HasColumnType("int")
                        .HasColumnName("type_id");

                    b.Property<int>("ValueId")
                        .HasColumnType("int")
                        .HasColumnName("value_id");

                    b.HasKey("ProductTypeId", "TypeId", "ValueId");

                    b.HasIndex("ProductTypeId", "TypeId");

                    b.HasIndex("TypeId", "ValueId");

                    b.ToTable("lookup_allowed", "catalog");
                });

            modelBuilder.Entity("Peers.Modules.Catalog.Domain.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsSelectable")
                        .HasColumnType("bit")
                        .HasColumnName("is_selectable");

                    b.Property<int>("Kind")
                        .HasColumnType("int")
                        .HasColumnName("kind");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("parent_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("slug");

                    b.Property<string>("SlugPath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("slug_path");

                    b.Property<int>("State")
                        .HasColumnType("int")
                        .HasColumnName("state");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("SlugPath")
                        .IsUnique();

                    b.HasIndex("IsSelectable", "ParentId");

                    b.HasIndex("ParentId", "Slug", "Version")
                        .IsUnique()
                        .HasFilter("[parent_id] IS NOT NULL");

                    b.ToTable("product_type", "catalog");
                });

            modelBuilder.Entity("Peers.Modules.Catalog.Domain.Translations.AttributeDefinitionTr", b =>
                {
                    b.Property<int>("EntityId")
                        .HasColumnType("int")
                        .HasColumnName("entity_id");

                    b.Property<string>("LangCode")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("lang_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("name");

                    b.Property<string>("Unit")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("unit");

                    b.HasKey("EntityId", "LangCode");

                    b.HasIndex("LangCode");

                    b.ToTable("attribute_definition_tr", "i18n");
                });

            modelBuilder.Entity("Peers.Modules.Catalog.Domain.Translations.EnumAttributeOptionTr", b =>
                {
                    b.Property<int>("EntityId")
                        .HasColumnType("int")
                        .HasColumnName("entity_id");

                    b.Property<string>("LangCode")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("lang_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("name");

                    b.HasKey("EntityId", "LangCode");

                    b.HasIndex("LangCode");

                    b.ToTable("enum_attribute_option_tr", "i18n");
                });

            modelBuilder.Entity("Peers.Modules.Catalog.Domain.Translations.ProductTypeTr", b =>
                {
                    b.Property<int>("EntityId")
                        .HasColumnType("int")
                        .HasColumnName("entity_id");

                    b.Property<string>("LangCode")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("lang_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("name");

                    b.HasKey("EntityId", "LangCode");

                    b.HasIndex("LangCode");

                    b.ToTable("product_type_tr", "i18n");
                });

            modelBuilder.Entity("Peers.Modules.Customers.Domain.Customer", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("PinCodeHash")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("pin_code_hash");

                    b.Property<string>("Secret")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("secret");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("customer", (string)null);
                });

            modelBuilder.Entity("Peers.Modules.I18n.Domain.Language", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("language", "i18n");
                });

            modelBuilder.Entity("Peers.Modules.Kernel.PeersContext+ProductTypeLineageRow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("Lvl")
                        .HasColumnType("int")
                        .HasColumnName("lvl");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("parent_id");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.ToFunction("[catalog].[ufn_ProductTypeLineage]");
                });

            modelBuilder.Entity("Peers.Modules.Listings.Domain.Listing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "listing_seq");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("base_price");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("description");

                    b.Property<string>("Hashtag")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("hashtag");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("int")
                        .HasColumnName("product_type_id");

                    b.Property<int>("ProductTypeVersion")
                        .HasColumnType("int")
                        .HasColumnName("product_type_version");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<int>("SellerId")
                        .HasColumnType("int")
                        .HasColumnName("seller_id");

                    b.Property<int>("State")
                        .HasColumnType("int")
                        .HasColumnName("state");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "OrderQty", "Peers.Modules.Listings.Domain.Listing.OrderQty#OrderQtyPolicy", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int?>("Max")
                                .HasColumnType("int")
                                .HasColumnName("max_order_qty");

                            b1.Property<int?>("Min")
                                .HasColumnType("int")
                                .HasColumnName("min_order_qty");
                        });

                    b.HasKey("Id");

                    b.HasIndex("ProductTypeId");

                    b.HasIndex("SellerId", "Hashtag")
                        .IsUnique()
                        .HasFilter("[hashtag] IS NOT NULL");

                    b.ToTable("listing", null, t =>
                        {
                            t.HasCheckConstraint("CK_Listing_BasePrice_NonNegative", "[base_price] >= 0");

                            t.HasCheckConstraint("CK_Listing_OrderQty", "([min_order_qty] IS NULL OR [min_order_qty] >= 1)\r\nAND ([max_order_qty] IS NULL OR [max_order_qty] >= 1)\r\nAND ([min_order_qty] IS NULL OR [max_order_qty] IS NULL OR [max_order_qty] >= [min_order_qty])");
                        });
                });

            modelBuilder.Entity("Peers.Modules.Listings.Domain.ListingVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("InventoryQty")
                        .HasColumnType("int")
                        .HasColumnName("inventory_qty");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<int>("ListingId")
                        .HasColumnType("int")
                        .HasColumnName("listing_id");

                    b.Property<decimal?>("PriceOverride")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price_override");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<string>("SkuCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("sku_code");

                    b.Property<string>("VariantKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("variant_key");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("ListingId", "SkuCode")
                        .IsUnique();

                    b.HasIndex("ListingId", "VariantKey")
                        .IsUnique();

                    b.ToTable("listing_variant", (string)null);
                });

            modelBuilder.Entity("Peers.Modules.Listings.Domain.Translations.ListingTr", b =>
                {
                    b.Property<int>("EntityId")
                        .HasColumnType("int")
                        .HasColumnName("entity_id");

                    b.Property<string>("LangCode")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("lang_code");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("description");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("title");

                    b.HasKey("EntityId", "LangCode");

                    b.HasIndex("LangCode");

                    b.ToTable("listing_tr", "i18n");
                });

            modelBuilder.Entity("Peers.Modules.Lookup.Domain.LookupLink", b =>
                {
                    b.Property<int>("ParentTypeId")
                        .HasColumnType("int")
                        .HasColumnName("parent_type_id");

                    b.Property<int>("ParentValueId")
                        .HasColumnType("int")
                        .HasColumnName("parent_value_id");

                    b.Property<int>("ChildTypeId")
                        .HasColumnType("int")
                        .HasColumnName("child_type_id");

                    b.Property<int>("ChildValueId")
                        .HasColumnType("int")
                        .HasColumnName("child_value_id");

                    b.HasKey("ParentTypeId", "ParentValueId", "ChildTypeId", "ChildValueId");

                    b.HasIndex("ChildTypeId", "ChildValueId");

                    b.ToTable("lookup_link", "lookup");
                });

            modelBuilder.Entity("Peers.Modules.Lookup.Domain.LookupType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConstraintMode")
                        .HasColumnType("int")
                        .HasColumnName("constraint_mode");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("key");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("lookup_type", "lookup");
                });

            modelBuilder.Entity("Peers.Modules.Lookup.Domain.LookupValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("key");

                    b.Property<int>("TypeId")
                        .HasColumnType("int")
                        .HasColumnName("type_id");

                    b.HasKey("Id");

                    b.HasIndex("TypeId", "Key")
                        .IsUnique();

                    b.ToTable("lookup_value", "lookup");
                });

            modelBuilder.Entity("Peers.Modules.Lookup.Domain.Translations.LookupValueTr", b =>
                {
                    b.Property<int>("EntityId")
                        .HasColumnType("int")
                        .HasColumnName("entity_id");

                    b.Property<string>("LangCode")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("lang_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("name");

                    b.HasKey("EntityId", "LangCode");

                    b.HasIndex("LangCode");

                    b.ToTable("lookup_value_tr", "i18n");
                });

            modelBuilder.Entity("Peers.Modules.Media.Domain.MediaFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Approved")
                        .HasColumnType("bit")
                        .HasColumnName("approved");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("batch_id");

                    b.Property<int>("Category")
                        .HasColumnType("int")
                        .HasColumnName("category");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("description");

                    b.Property<string>("MediaUrl")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("media_url");

                    b.Property<long?>("SizeInBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_in_bytes");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<int?>("ThumbnailId")
                        .HasColumnType("int")
                        .HasColumnName("thumbnail_id");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Approved");

                    b.HasIndex("BatchId");

                    b.HasIndex("Category");

                    b.HasIndex("CustomerId");

                    b.HasIndex("Status");

                    b.HasIndex("ThumbnailId")
                        .IsUnique()
                        .HasFilter("[thumbnail_id] IS NOT NULL");

                    b.HasIndex("Type");

                    b.HasIndex("Type", "ThumbnailId", "CustomerId")
                        .IsUnique()
                        .HasFilter("[type] = 0");

                    b.ToTable("media_file", "dbo");
                });

            modelBuilder.Entity("Peers.Modules.Settings.Domain.PrivacyPolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date");

                    b.HasKey("Id");

                    b.ToTable("privacy_policy", "settings");
                });

            modelBuilder.Entity("Peers.Modules.Settings.Domain.PrivacyPolicyTr", b =>
                {
                    b.Property<int>("EntityId")
                        .HasColumnType("int")
                        .HasColumnName("entity_id");

                    b.Property<string>("LangCode")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("lang_code");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("body");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("title");

                    b.HasKey("EntityId", "LangCode");

                    b.HasIndex("LangCode");

                    b.ToTable("privacy_policy_tr", "i18n");
                });

            modelBuilder.Entity("Peers.Modules.Settings.Domain.Terms", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("terms", "settings");
                });

            modelBuilder.Entity("Peers.Modules.Settings.Domain.TermsTr", b =>
                {
                    b.Property<int>("EntityId")
                        .HasColumnType("int")
                        .HasColumnName("entity_id");

                    b.Property<string>("LangCode")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("lang_code");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("body");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("title");

                    b.HasKey("EntityId", "LangCode");

                    b.HasIndex("LangCode");

                    b.ToTable("terms_tr", "i18n");
                });

            modelBuilder.Entity("Peers.Modules.System.Domain.ClientAppInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("id");

                    b.Property<string>("AndroidStoreLink")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("android_store_link");

                    b.Property<string>("HashString")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("hash_string");

                    b.Property<string>("IOSStoreLink")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("ios_store_link");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("package_name");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "LatestVersion", "Peers.Modules.System.Domain.ClientAppInfo.LatestVersion#ClientAppVersion", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Build")
                                .HasColumnType("int")
                                .HasColumnName("build");

                            b1.Property<int>("Major")
                                .HasColumnType("int")
                                .HasColumnName("major");

                            b1.Property<int>("Minor")
                                .HasColumnType("int")
                                .HasColumnName("minor");

                            b1.Property<int>("Revision")
                                .HasColumnType("int")
                                .HasColumnName("revision");
                        });

                    b.HasKey("Id");

                    b.HasIndex("AndroidStoreLink")
                        .IsUnique();

                    b.HasIndex("HashString")
                        .IsUnique();

                    b.HasIndex("IOSStoreLink")
                        .IsUnique();

                    b.HasIndex("PackageName")
                        .IsUnique();

                    b.ToTable("client_app_info", (string)null);
                });

            modelBuilder.Entity("Peers.Modules.Users.Domain.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "app_user_seq");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_on");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("firstname");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Lastname")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("lastname");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("OriginalDeletedUsername")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("original_deleted_username");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("preferred_language");

                    b.Property<DateTime>("RegisteredOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("registered_on");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("security_stamp");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UpdatedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("updated_email");

                    b.Property<string>("UserName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[normalized_user_name] IS NOT NULL");

                    b.HasIndex("Status");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasFilter("[user_name] IS NOT NULL");

                    b.ToTable("app_user", "id");
                });

            modelBuilder.Entity("Peers.Modules.Users.Domain.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("App")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("app");

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("app_version");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("device_id");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("device_type");

                    b.Property<string>("Idiom")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("idiom");

                    b.Property<DateTime?>("LastPing")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_ping");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("model");

                    b.Property<string>("OSVersion")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("os_version");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("platform");

                    b.Property<string>("PnsHandle")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("pns_handle");

                    b.Property<DateTime>("PnsHandleLastRefreshed")
                        .HasColumnType("datetime2")
                        .HasColumnName("pns_handle_last_refreshed");

                    b.Property<DateTime>("PnsHandleTimestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("pns_handle_timestamp");

                    b.Property<DateTime>("RegisteredOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("registered_on");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.HasIndex("PnsHandle")
                        .IsUnique()
                        .HasFilter("[pns_handle] IS NOT NULL");

                    b.HasIndex("UserId");

                    b.ToTable("device", "dbo");
                });

            modelBuilder.Entity("Peers.Modules.Users.Domain.DeviceError", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppState")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("app_state");

                    b.Property<string>("AppVersion")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("app_version");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("device_id");

                    b.Property<string>("DeviceInfo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("device_info");

                    b.Property<string>("Exception")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("exception");

                    b.Property<string>("Info")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("info");

                    b.Property<string>("Locale")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("locale");

                    b.Property<DateTime>("ReportedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("reported_on");

                    b.Property<bool>("Silent")
                        .HasColumnType("bit")
                        .HasColumnName("silent");

                    b.Property<string>("Source")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("source");

                    b.Property<string>("StackTrace")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("stack_trace");

                    b.Property<string>("Username")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("device_error", "dbo");
                });

            modelBuilder.Entity("Peers.Modules.Users.Domain.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contents")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contents");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_on");

                    b.HasKey("Id");

                    b.ToTable("notification", (string)null);
                });

            modelBuilder.Entity("Peers.Modules.Users.Domain.PushNotificationProblem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ErrorCode")
                        .HasColumnType("int")
                        .HasColumnName("error_code");

                    b.Property<int?>("MessagingErrorCode")
                        .HasColumnType("int")
                        .HasColumnName("messaging_error_code");

                    b.Property<DateTime>("ReportedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("reported_on");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("token");

                    b.HasKey("Id");

                    b.HasIndex("ErrorCode");

                    b.HasIndex("Token");

                    b.ToTable("push_notification_problem", "dbo");
                });

            modelBuilder.Entity("Peers.Modules.Users.Domain.UserNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit")
                        .HasColumnName("is_read");

                    b.Property<int>("notification_id")
                        .HasColumnType("int")
                        .HasColumnName("notification_id");

                    b.Property<int>("user_id")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("notification_id");

                    b.HasIndex("user_id");

                    b.ToTable("user_notification", (string)null);
                });

            modelBuilder.Entity("Peers.Modules.Users.Domain.UserStatusChange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeReason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("change_reason");

                    b.Property<int>("ChangedById")
                        .HasColumnType("int")
                        .HasColumnName("changed_by_id");

                    b.Property<DateTime>("ChangedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("changed_on");

                    b.Property<int>("NewStatus")
                        .HasColumnType("int")
                        .HasColumnName("new_status");

                    b.Property<int>("OldStatus")
                        .HasColumnType("int")
                        .HasColumnName("old_status");

                    b.Property<int>("user_id")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ChangedById");

                    b.HasIndex("user_id");

                    b.ToTable("user_status_change_history", (string)null);
                });

            modelBuilder.Entity("Peers.Modules.Catalog.Domain.Attributes.BoolAttributeDefinition", b =>
                {
                    b.HasBaseType("Peers.Modules.Catalog.Domain.Attributes.AttributeDefinition");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_AD_IsVariant_EnumOnly", "[is_variant] = 0 OR [kind] = 5");

                            t.HasCheckConstraint("CK_AD_LookupTypeId_LookupOnly", "(\r\n    ([kind] = 6 AND [lookup_type_id] IS NOT NULL)\r\n    OR\r\n    ([kind] <> 6 AND [lookup_type_id] IS NULL)\r\n)");
                        });

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("Peers.Modules.Catalog.Domain.Attributes.DateAttributeDefinition", b =>
                {
                    b.HasBaseType("Peers.Modules.Catalog.Domain.Attributes.AttributeDefinition");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_AD_IsVariant_EnumOnly", "[is_variant] = 0 OR [kind] = 5");

                            t.HasCheckConstraint("CK_AD_LookupTypeId_LookupOnly", "(\r\n    ([kind] = 6 AND [lookup_type_id] IS NOT NULL)\r\n    OR\r\n    ([kind] <> 6 AND [lookup_type_id] IS NULL)\r\n)");
                        });

                    b.HasDiscriminator().HasValue(4);
                });

            modelBuilder.Entity("Peers.Modules.Catalog.Domain.Attributes.DecimalAttributeDefinition", b =>
                {
                    b.HasBaseType("Peers.Modules.Catalog.Domain.Attributes.AttributeDefinition");

                    b.Property<string>("Config")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("config");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_AD_IsVariant_EnumOnly", "[is_variant] = 0 OR [kind] = 5");

                            t.HasCheckConstraint("CK_AD_LookupTypeId_LookupOnly", "(\r\n    ([kind] = 6 AND [lookup_type_id] IS NOT NULL)\r\n    OR\r\n    ([kind] <> 6 AND [lookup_type_id] IS NULL)\r\n)");
                        });

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Peers.Modules.Catalog.Domain.Attributes.DependentAttributeDefinition", b =>
                {
                    b.HasBaseType("Peers.Modules.Catalog.Domain.Attributes.AttributeDefinition");

                    b.Property<int?>("DependsOnId")
                        .HasColumnType("int")
                        .HasColumnName("depends_on_id");

                    b.HasIndex("DependsOnId");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_AD_IsVariant_EnumOnly", "[is_variant] = 0 OR [kind] = 5");

                            t.HasCheckConstraint("CK_AD_LookupTypeId_LookupOnly", "(\r\n    ([kind] = 6 AND [lookup_type_id] IS NOT NULL)\r\n    OR\r\n    ([kind] <> 6 AND [lookup_type_id] IS NULL)\r\n)");
                        });
                });

            modelBuilder.Entity("Peers.Modules.Catalog.Domain.Attributes.IntAttributeDefinition", b =>
                {
                    b.HasBaseType("Peers.Modules.Catalog.Domain.Attributes.AttributeDefinition");

                    b.Property<string>("Config")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("config");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_AD_IsVariant_EnumOnly", "[is_variant] = 0 OR [kind] = 5");

                            t.HasCheckConstraint("CK_AD_LookupTypeId_LookupOnly", "(\r\n    ([kind] = 6 AND [lookup_type_id] IS NOT NULL)\r\n    OR\r\n    ([kind] <> 6 AND [lookup_type_id] IS NULL)\r\n)");
                        });

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("Peers.Modules.Catalog.Domain.Attributes.StringAttributeDefinition", b =>
                {
                    b.HasBaseType("Peers.Modules.Catalog.Domain.Attributes.AttributeDefinition");

                    b.Property<string>("Config")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("config");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_AD_IsVariant_EnumOnly", "[is_variant] = 0 OR [kind] = 5");

                            t.HasCheckConstraint("CK_AD_LookupTypeId_LookupOnly", "(\r\n    ([kind] = 6 AND [lookup_type_id] IS NOT NULL)\r\n    OR\r\n    ([kind] <> 6 AND [lookup_type_id] IS NULL)\r\n)");
                        });

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Peers.Modules.Catalog.Domain.Attributes.EnumAttributeDefinition", b =>
                {
                    b.HasBaseType("Peers.Modules.Catalog.Domain.Attributes.DependentAttributeDefinition");

                    b.Property<bool>("IsVariant")
                        .HasColumnType("bit")
                        .HasColumnName("is_variant");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_AD_IsVariant_EnumOnly", "[is_variant] = 0 OR [kind] = 5");

                            t.HasCheckConstraint("CK_AD_LookupTypeId_LookupOnly", "(\r\n    ([kind] = 6 AND [lookup_type_id] IS NOT NULL)\r\n    OR\r\n    ([kind] <> 6 AND [lookup_type_id] IS NULL)\r\n)");
                        });

                    b.HasDiscriminator().HasValue(5);
                });

            modelBuilder.Entity("Peers.Modules.Catalog.Domain.Attributes.LookupAttributeDefinition", b =>
                {
                    b.HasBaseType("Peers.Modules.Catalog.Domain.Attributes.DependentAttributeDefinition");

                    b.Property<string>("Config")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("config");

                    b.Property<int>("LookupTypeId")
                        .HasColumnType("int")
                        .HasColumnName("lookup_type_id");

                    b.HasIndex("LookupTypeId");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_AD_IsVariant_EnumOnly", "[is_variant] = 0 OR [kind] = 5");

                            t.HasCheckConstraint("CK_AD_LookupTypeId_LookupOnly", "(\r\n    ([kind] = 6 AND [lookup_type_id] IS NOT NULL)\r\n    OR\r\n    ([kind] <> 6 AND [lookup_type_id] IS NULL)\r\n)");
                        });

                    b.HasDiscriminator().HasValue(6);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Peers.Modules.Users.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Peers.Modules.Users.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Peers.Modules.Users.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Peers.Modules.Users.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Peers.Modules.Catalog.Domain.Attributes.AttributeDefinition", b =>
                {
                    b.HasOne("Peers.Modules.Catalog.Domain.ProductType", "ProductType")
                        .WithMany("Attributes")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("Peers.Modules.Catalog.Domain.Attributes.EnumAttributeOption", b =>
                {
                    b.HasOne("Peers.Modules.Catalog.Domain.Attributes.EnumAttributeDefinition", "EnumAttributeDefinition")
                        .WithMany("Options")
                        .HasForeignKey("EnumAttributeDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Peers.Modules.Catalog.Domain.Attributes.EnumAttributeOption", "ParentOption")
                        .WithMany()
                        .HasForeignKey("ParentOptionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EnumAttributeDefinition");

                    b.Navigation("ParentOption");
                });

            modelBuilder.Entity("Peers.Modules.Catalog.Domain.LookupAllowed", b =>
                {
                    b.HasOne("Peers.Modules.Catalog.Domain.ProductType", "ProductType")
                        .WithMany("LookupsAllowed")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Peers.Modules.Lookup.Domain.LookupValue", "Value")
                        .WithMany()
                        .HasForeignKey("TypeId", "ValueId")
                        .HasPrincipalKey("TypeId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductType");

                    b.Navigation("Value");
                });

            modelBuilder.Entity("Peers.Modules.Catalog.Domain.ProductType", b =>
                {
                    b.HasOne("Peers.Modules.Catalog.Domain.ProductType", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Peers.Modules.Catalog.Domain.Translations.AttributeDefinitionTr", b =>
                {
                    b.HasOne("Peers.Modules.Catalog.Domain.Attributes.AttributeDefinition", null)
                        .WithMany("Translations")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Peers.Modules.I18n.Domain.Language", null)
                        .WithMany()
                        .HasForeignKey("LangCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Peers.Modules.Catalog.Domain.Translations.EnumAttributeOptionTr", b =>
                {
                    b.HasOne("Peers.Modules.Catalog.Domain.Attributes.EnumAttributeOption", null)
                        .WithMany("Translations")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Peers.Modules.I18n.Domain.Language", null)
                        .WithMany()
                        .HasForeignKey("LangCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Peers.Modules.Catalog.Domain.Translations.ProductTypeTr", b =>
                {
                    b.HasOne("Peers.Modules.Catalog.Domain.ProductType", null)
                        .WithMany("Translations")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Peers.Modules.I18n.Domain.Language", null)
                        .WithMany()
                        .HasForeignKey("LangCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Peers.Modules.Customers.Domain.Customer", b =>
                {
                    b.HasOne("Peers.Modules.Users.Domain.AppUser", "User")
                        .WithOne()
                        .HasForeignKey("Peers.Modules.Customers.Domain.Customer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Peers.Modules.Listings.Domain.Listing", b =>
                {
                    b.HasOne("Peers.Modules.Catalog.Domain.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Peers.Modules.Customers.Domain.Customer", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("Peers.Modules.Listings.Domain.ListingAttribute", "Attributes", b1 =>
                        {
                            b1.Property<int>("ListingId")
                                .HasColumnType("int")
                                .HasColumnName("listing_id");

                            b1.Property<int>("AttributeDefinitionId")
                                .HasColumnType("int")
                                .HasColumnName("attribute_definition_id");

                            b1.Property<int>("AttributeKind")
                                .HasColumnType("int")
                                .HasColumnName("attribute_kind");

                            b1.Property<int?>("EnumAttributeOptionId")
                                .HasColumnType("int")
                                .HasColumnName("enum_attribute_option_id");

                            b1.Property<int?>("LookupValueId")
                                .HasColumnType("int")
                                .HasColumnName("lookup_value_id");

                            b1.Property<int>("Position")
                                .HasColumnType("int")
                                .HasColumnName("position");

                            b1.Property<string>("Value")
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasColumnName("value");

                            b1.HasKey("ListingId", "AttributeDefinitionId");

                            b1.HasIndex("AttributeDefinitionId");

                            b1.HasIndex("EnumAttributeOptionId");

                            b1.HasIndex("LookupValueId");

                            b1.HasIndex("ListingId", "EnumAttributeOptionId")
                                .IsUnique()
                                .HasFilter("[enum_attribute_option_id] IS NOT NULL");

                            b1.HasIndex("ListingId", "LookupValueId")
                                .IsUnique()
                                .HasFilter("[lookup_value_id] IS NOT NULL");

                            b1.ToTable("listing_attribute", null, t =>
                                {
                                    t.HasCheckConstraint("CK_LA_OnePayload", "(\r\n    [attribute_kind] IN (0,1,2,3,4) AND [value] IS NOT NULL\r\n    AND [enum_attribute_option_id] IS NULL AND [lookup_value_id] IS NULL\r\n)\r\nOR\r\n(\r\n    [attribute_kind] = 5 AND [enum_attribute_option_id] IS NOT NULL\r\n    AND [value] IS NULL AND [lookup_value_id] IS NULL\r\n)\r\nOR\r\n(\r\n    [attribute_kind] = 6 AND [lookup_value_id] IS NOT NULL\r\n    AND [value] IS NULL AND [enum_attribute_option_id] IS NULL\r\n)");

                                    t.HasCheckConstraint("CK_LA_Position_NonNegative", "[position] >= 0");
                                });

                            b1.HasOne("Peers.Modules.Catalog.Domain.Attributes.AttributeDefinition", "AttributeDefinition")
                                .WithMany()
                                .HasForeignKey("AttributeDefinitionId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.HasOne("Peers.Modules.Catalog.Domain.Attributes.EnumAttributeOption", "EnumAttributeOption")
                                .WithMany()
                                .HasForeignKey("EnumAttributeOptionId")
                                .OnDelete(DeleteBehavior.Restrict);

                            b1.WithOwner("Listing")
                                .HasForeignKey("ListingId");

                            b1.HasOne("Peers.Modules.Lookup.Domain.LookupValue", "LookupValue")
                                .WithMany()
                                .HasForeignKey("LookupValueId")
                                .OnDelete(DeleteBehavior.Restrict);

                            b1.Navigation("AttributeDefinition");

                            b1.Navigation("EnumAttributeOption");

                            b1.Navigation("Listing");

                            b1.Navigation("LookupValue");
                        });

                    b.Navigation("Attributes");

                    b.Navigation("ProductType");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("Peers.Modules.Listings.Domain.ListingVariant", b =>
                {
                    b.HasOne("Peers.Modules.Listings.Domain.Listing", "Listing")
                        .WithMany("Variants")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Peers.Modules.Listings.Domain.ListingVariantAttribute", "Attributes", b1 =>
                        {
                            b1.Property<int>("ListingVariantId")
                                .HasColumnType("int")
                                .HasColumnName("listing_variant_id");

                            b1.Property<int>("AttributeDefinitionId")
                                .HasColumnType("int")
                                .HasColumnName("attribute_definition_id");

                            b1.Property<int>("AttributeOptionId")
                                .HasColumnType("int")
                                .HasColumnName("attribute_option_id");

                            b1.Property<int>("Position")
                                .HasColumnType("int")
                                .HasColumnName("position");

                            b1.HasKey("ListingVariantId", "AttributeDefinitionId");

                            b1.HasIndex("AttributeDefinitionId");

                            b1.HasIndex("AttributeOptionId");

                            b1.HasIndex("ListingVariantId", "AttributeOptionId")
                                .IsUnique();

                            b1.ToTable("listing_variant_attribute", null, t =>
                                {
                                    t.HasCheckConstraint("CK_LVA_Position_NonNegative", "[position] >= 0");
                                });

                            b1.HasOne("Peers.Modules.Catalog.Domain.Attributes.AttributeDefinition", "AttributeDefinition")
                                .WithMany()
                                .HasForeignKey("AttributeDefinitionId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.HasOne("Peers.Modules.Catalog.Domain.Attributes.EnumAttributeOption", "EnumAttributeOption")
                                .WithMany()
                                .HasForeignKey("AttributeOptionId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner("ListingVariant")
                                .HasForeignKey("ListingVariantId");

                            b1.Navigation("AttributeDefinition");

                            b1.Navigation("EnumAttributeOption");

                            b1.Navigation("ListingVariant");
                        });

                    b.Navigation("Attributes");

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("Peers.Modules.Listings.Domain.Translations.ListingTr", b =>
                {
                    b.HasOne("Peers.Modules.Listings.Domain.Listing", null)
                        .WithMany("Translations")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Peers.Modules.I18n.Domain.Language", null)
                        .WithMany()
                        .HasForeignKey("LangCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Peers.Modules.Lookup.Domain.LookupLink", b =>
                {
                    b.HasOne("Peers.Modules.Lookup.Domain.LookupValue", "ChildValue")
                        .WithMany()
                        .HasForeignKey("ChildTypeId", "ChildValueId")
                        .HasPrincipalKey("TypeId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Peers.Modules.Lookup.Domain.LookupValue", "ParentValue")
                        .WithMany()
                        .HasForeignKey("ParentTypeId", "ParentValueId")
                        .HasPrincipalKey("TypeId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChildValue");

                    b.Navigation("ParentValue");
                });

            modelBuilder.Entity("Peers.Modules.Lookup.Domain.LookupValue", b =>
                {
                    b.HasOne("Peers.Modules.Lookup.Domain.LookupType", "Type")
                        .WithMany("Values")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Peers.Modules.Lookup.Domain.Translations.LookupValueTr", b =>
                {
                    b.HasOne("Peers.Modules.Lookup.Domain.LookupValue", null)
                        .WithMany("Translations")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Peers.Modules.I18n.Domain.Language", null)
                        .WithMany()
                        .HasForeignKey("LangCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Peers.Modules.Media.Domain.MediaFile", b =>
                {
                    b.HasOne("Peers.Modules.Customers.Domain.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Peers.Modules.Media.Domain.MediaFile", "Thumbnail")
                        .WithOne("Original")
                        .HasForeignKey("Peers.Modules.Media.Domain.MediaFile", "ThumbnailId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Customer");

                    b.Navigation("Thumbnail");
                });

            modelBuilder.Entity("Peers.Modules.Settings.Domain.PrivacyPolicyTr", b =>
                {
                    b.HasOne("Peers.Modules.Settings.Domain.PrivacyPolicy", null)
                        .WithMany("Translations")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Peers.Modules.I18n.Domain.Language", null)
                        .WithMany()
                        .HasForeignKey("LangCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Peers.Modules.Settings.Domain.TermsTr", b =>
                {
                    b.HasOne("Peers.Modules.Settings.Domain.Terms", null)
                        .WithMany("Translations")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Peers.Modules.I18n.Domain.Language", null)
                        .WithMany()
                        .HasForeignKey("LangCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Peers.Modules.Users.Domain.AppUser", b =>
                {
                    b.OwnsMany("Peers.Modules.Users.Domain.AppUsageHistory", "AppUsage", b1 =>
                        {
                            b1.Property<int>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasColumnName("id");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("id"));

                            b1.Property<DateTime>("OpenedAt")
                                .HasColumnType("datetime2")
                                .HasColumnName("opened_at");

                            b1.Property<int>("user_id")
                                .HasColumnType("int")
                                .HasColumnName("user_id");

                            b1.HasKey("id");

                            b1.HasIndex("user_id");

                            b1.ToTable("app_usage_history", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("user_id");
                        });

                    b.OwnsMany("Peers.Modules.Users.Domain.RefreshToken", "RefreshTokens", b1 =>
                        {
                            b1.Property<int>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasColumnName("id");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("id"));

                            b1.Property<DateTime>("Created")
                                .HasColumnType("datetime2")
                                .HasColumnName("created");

                            b1.Property<DateTime?>("Revoked")
                                .HasColumnType("datetime2")
                                .HasColumnName("revoked");

                            b1.Property<string>("Token")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasColumnName("token");

                            b1.Property<byte[]>("concurrency_token")
                                .IsConcurrencyToken()
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("rowversion")
                                .HasColumnName("concurrency_token");

                            b1.Property<int>("user_id")
                                .HasColumnType("int")
                                .HasColumnName("user_id");

                            b1.HasKey("id");

                            b1.HasIndex("Revoked");

                            b1.HasIndex("user_id");

                            b1.ToTable("refresh_token", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("user_id");
                        });

                    b.Navigation("AppUsage");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("Peers.Modules.Users.Domain.Device", b =>
                {
                    b.HasOne("Peers.Modules.Users.Domain.AppUser", "User")
                        .WithMany("DeviceList")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Peers.Modules.Users.Domain.UserNotification", b =>
                {
                    b.HasOne("Peers.Modules.Users.Domain.Notification", "Notification")
                        .WithMany()
                        .HasForeignKey("notification_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Peers.Modules.Users.Domain.AppUser", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notification");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Peers.Modules.Users.Domain.UserStatusChange", b =>
                {
                    b.HasOne("Peers.Modules.Users.Domain.AppUser", "ChangedBy")
                        .WithMany()
                        .HasForeignKey("ChangedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Peers.Modules.Users.Domain.AppUser", null)
                        .WithMany("StatusChangeHistory")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedBy");
                });

            modelBuilder.Entity("Peers.Modules.Catalog.Domain.Attributes.DependentAttributeDefinition", b =>
                {
                    b.HasOne("Peers.Modules.Catalog.Domain.Attributes.DependentAttributeDefinition", "DependsOn")
                        .WithMany()
                        .HasForeignKey("DependsOnId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DependsOn");
                });

            modelBuilder.Entity("Peers.Modules.Catalog.Domain.Attributes.LookupAttributeDefinition", b =>
                {
                    b.HasOne("Peers.Modules.Lookup.Domain.LookupType", "LookupType")
                        .WithMany()
                        .HasForeignKey("LookupTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LookupType");
                });

            modelBuilder.Entity("Peers.Modules.Catalog.Domain.Attributes.AttributeDefinition", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Peers.Modules.Catalog.Domain.Attributes.EnumAttributeOption", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Peers.Modules.Catalog.Domain.ProductType", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("Children");

                    b.Navigation("LookupsAllowed");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Peers.Modules.Listings.Domain.Listing", b =>
                {
                    b.Navigation("Translations");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("Peers.Modules.Lookup.Domain.LookupType", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("Peers.Modules.Lookup.Domain.LookupValue", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Peers.Modules.Media.Domain.MediaFile", b =>
                {
                    b.Navigation("Original");
                });

            modelBuilder.Entity("Peers.Modules.Settings.Domain.PrivacyPolicy", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Peers.Modules.Settings.Domain.Terms", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Peers.Modules.Users.Domain.AppUser", b =>
                {
                    b.Navigation("DeviceList");

                    b.Navigation("Notifications");

                    b.Navigation("StatusChangeHistory");
                });

            modelBuilder.Entity("Peers.Modules.Catalog.Domain.Attributes.EnumAttributeDefinition", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
