import { library } from '@fortawesome/fontawesome-svg-core';
import {
    faCopyright as farCopyright,
    faUser as farUser,
} from '@fortawesome/free-regular-svg-icons';
import {
    faArrowUpRightFromSquare as fasArrowUpRightFromSquare,
    faArrowLeft as fasArrowLeft,
    faArrowRight as fasArrowRight,
    faExplosion as fasExplosion,
    faPencil as fasPencil,
    faCancel as fasCancel,
    faSave as fasSave,
    faCheckCircle as fasCheckCircle,
    faCircleXmark as fasCircleXmark,
    faClock as fasClock,
    faCopyright as fasCopyright,
    faUser as fasUser,
    faEnvelopeSquare as fasEnvelopeSquare,
    faKey as fasKey,
    faExclamationTriangle as fasExclamationTriangle,
    faUserSlash as fasUserSlash,
    faCircleExclamation as fasCircleExclamation,
    faHourglass as fasHourglass,
    faHourglassHalf as fasHourglassHalf,
    faCarOn as fasCarOn,
    faMobileScreen as fasMobileScreen,
    faScrewdriverWrench as fasScrewdriverWrench,
    faInfo as fasInfo,
    faScissors as fasScissors,
    faEdit as fasEdit,
    faFileCircleExclamation as fasFileCircleExclamation,
    faCircle as fasCircle,
    faMobileScreenButton as fasMobileScreenButton,

    faMobile as fasMobile,
    faPowerOff as fasPowerOff,
    faGauge as fasGauge,
    faUserGroup as fasUserGroup,
    faChalkboardUser as fasChalkboardUser,
    faBell as fasBell,
    faFile as fasFile,
    faMagnifyingGlass as fasMagnifyingGlass,
    faQuestionCircle as fasQuestionCircle,

    faFont as fasFont,
    faLessThan as fasLessThan,
    faLessThanEqual as fasLessThanEqual,
    faEquals as fasEquals,
    faGreaterThanEqual as fasGreaterThanEqual,
    faGreaterThan as fasGreatherThan,
    faNotEqual as fasNotEqual,
    faPlus as fasPlus,
    faCircleCheck as fasCircleCheck,
    faMinusCircle as fasMinusCircle,
    faArrowRightFromBracket as fasArrowFromLeft,
    faArrowRightToBracket as fasArrowToRight,
    faTachometerAlt as fasTachometerAlt,
    faCogs as fasCogs,
    faMoneyBillTrendUp as fasMoneyBillTrendUp,
    faHomeLg as fasHomeLg,
    faClipboardCheck as fasClipboardListCheck,
    faTrashAlt as fasTrashAlt,
    faFileExport as fasFileExport,
    faEnvelopeOpenText as fasEnvelopeOpenText,

    faUsers as fasUsers,
    faMapLocationDot as fasMapLocationDot,
    faTruckRampBox as fasTruckRampBox,
    faTruck as fasTruck,
    faPeopleCarryBox as fasPeopleCarryBox,
    faHandshake as fasHandshake,
    faCartFlatbed as fasCartFlatbed,

    faFingerprint as fasFingerprint,
    faIdCard as fasIdCard,
    faCarCrash as fasCarCrash,
    faIdCardClip as fasIdCardClip,

    faTicket as fasTicket,
    faLocationDot as fasLocationDot,
    faCheck as fasCheck,
    faCheckDouble as fasCheckDouble,
    faBan as fasBan,
    faStarHalfStroke as fasStarHalfStroke,
    faHandHoldingDollar as fasHandHoldingDollar,
    faScaleBalanced as fasScaleBalanced,
    faBook as fasBook,
    faMoneyBillTransfer as fasMoneyBillTransfer,
    faCreditCard as fasCreditCard,
    faReceipt as fasReceipt,
    faMoneyCheckDollar as fasMoneyCheckDollar,
    faSackDollar as fasSackDollar,

    faBank as fasBank,
    faCar as fasCar,
    faTruckPickup as fasTruckPickup,
    faListCheck as fasListCheck,
    faCalculator as fasCalculator,
    faRightLeft as fasRightLeft,
    faRectangleXmark as fasRectangleXmark,
    faCircleQuestion as fasCircleQuestion,
    faUpload as fasUpload,
    faUserLock as fasUserLock,
    faEnvelope as fasEnvelope,
    faArrowDown as fasArrowDown,
    faArrowUp as fasArrowUp,
    faTrash as fasTrash,
    faHeartPulse as fasHeartPulse,
} from '@fortawesome/free-solid-svg-icons';

library.add(
    fasArrowUpRightFromSquare,
    fasArrowLeft,
    fasArrowRight,
    fasExplosion,
    fasPencil,
    fasCancel,
    fasSave,
    fasCheckCircle,
    fasCircleXmark,
    fasClock,
    farCopyright,
    farUser,
    fasEnvelopeSquare,
    fasCopyright,
    fasUser,
    fasKey,
    fasMobile,
    fasPowerOff,
    fasGauge,
    fasUserGroup,
    fasChalkboardUser,
    fasBell,
    fasExclamationTriangle,
    fasFile,
    fasMagnifyingGlass,
    fasQuestionCircle,
    fasUserSlash,
    fasCircleExclamation,
    fasHourglass,
    fasHourglassHalf,
    fasCarOn,
    fasMobileScreen,
    fasScrewdriverWrench,
    fasInfo,
    fasScissors,
    fasEdit,
    fasFileCircleExclamation,
    fasCircle,
    fasMobileScreenButton,

    fasFont,
    fasLessThan,
    fasLessThanEqual,
    fasEquals,
    fasGreaterThanEqual,
    fasGreatherThan,
    fasNotEqual,
    fasPlus,
    fasCircleCheck,
    fasMinusCircle,
    fasArrowFromLeft,
    fasArrowToRight,
    fasTachometerAlt,
    fasCogs,
    fasMoneyBillTrendUp,
    fasHomeLg,
    fasClipboardListCheck,
    fasTrashAlt,
    fasFileExport,
    fasEnvelopeOpenText,

    fasUsers,
    fasMapLocationDot,
    fasTruckRampBox,
    fasTruck,
    fasPeopleCarryBox,
    fasHandshake,
    fasCartFlatbed,

    fasFingerprint,
    fasIdCard,
    fasCarCrash,
    fasIdCardClip,

    fasTicket,
    fasLocationDot,
    fasCheck,
    fasCheckDouble,
    fasBan,
    fasStarHalfStroke,
    fasHandHoldingDollar,
    fasScaleBalanced,
    fasBook,
    fasMoneyBillTransfer,
    fasCreditCard,
    fasReceipt,
    fasMoneyCheckDollar,
    fasSackDollar,

    fasBank,
    fasCar,
    fasTruckPickup,
    fasListCheck,
    fasCalculator,
    fasRightLeft,
    fasRectangleXmark,
    fasCircleQuestion,
    fasUpload,
    fasUserLock,
    fasEnvelope,

    fasArrowDown,
    fasArrowUp,
    fasTrash,
    fasHeartPulse,
);
